version: '3'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_CONNECTION: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB_NAME}
      JWT_TOKEN_SECRET: ${JWT_TOKEN_SECRET}
      JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}
      JWT_REFRESH_TOKEN_LIFE: ${JWT_REFRESH_TOKEN_LIFE}
      JWT_TOKEN_LIFE: ${JWT_TOKEN_LIFE}
      OTP_URL: ${OTP_URL}
      SMS_OTP_APIKEY: ${SMS_OTP_APIKEY}

volumes:
  db-data:
